/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LightweightRouteImport } from './routes/lightweight'
import { Route as HeavyDutyRouteImport } from './routes/heavy-duty'
import { Route as EvsRouteImport } from './routes/evs'
import { Route as AllInOneRouteImport } from './routes/all-in-one'
import { Route as IndexRouteImport } from './routes/index'

const LightweightRoute = LightweightRouteImport.update({
  id: '/lightweight',
  path: '/lightweight',
  getParentRoute: () => rootRouteImport,
} as any)
const HeavyDutyRoute = HeavyDutyRouteImport.update({
  id: '/heavy-duty',
  path: '/heavy-duty',
  getParentRoute: () => rootRouteImport,
} as any)
const EvsRoute = EvsRouteImport.update({
  id: '/evs',
  path: '/evs',
  getParentRoute: () => rootRouteImport,
} as any)
const AllInOneRoute = AllInOneRouteImport.update({
  id: '/all-in-one',
  path: '/all-in-one',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-in-one': typeof AllInOneRoute
  '/evs': typeof EvsRoute
  '/heavy-duty': typeof HeavyDutyRoute
  '/lightweight': typeof LightweightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-in-one': typeof AllInOneRoute
  '/evs': typeof EvsRoute
  '/heavy-duty': typeof HeavyDutyRoute
  '/lightweight': typeof LightweightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/all-in-one': typeof AllInOneRoute
  '/evs': typeof EvsRoute
  '/heavy-duty': typeof HeavyDutyRoute
  '/lightweight': typeof LightweightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/all-in-one' | '/evs' | '/heavy-duty' | '/lightweight'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all-in-one' | '/evs' | '/heavy-duty' | '/lightweight'
  id: '__root__' | '/' | '/all-in-one' | '/evs' | '/heavy-duty' | '/lightweight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllInOneRoute: typeof AllInOneRoute
  EvsRoute: typeof EvsRoute
  HeavyDutyRoute: typeof HeavyDutyRoute
  LightweightRoute: typeof LightweightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lightweight': {
      id: '/lightweight'
      path: '/lightweight'
      fullPath: '/lightweight'
      preLoaderRoute: typeof LightweightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heavy-duty': {
      id: '/heavy-duty'
      path: '/heavy-duty'
      fullPath: '/heavy-duty'
      preLoaderRoute: typeof HeavyDutyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evs': {
      id: '/evs'
      path: '/evs'
      fullPath: '/evs'
      preLoaderRoute: typeof EvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-in-one': {
      id: '/all-in-one'
      path: '/all-in-one'
      fullPath: '/all-in-one'
      preLoaderRoute: typeof AllInOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllInOneRoute: AllInOneRoute,
  EvsRoute: EvsRoute,
  HeavyDutyRoute: HeavyDutyRoute,
  LightweightRoute: LightweightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
